### PR TITLE
Use netifaces2 instead of netifaces

### PR DESCRIPTION
**Pull request by leoplo**
Use netifaces2 instead of netifaces to support Python 3.11

### CODE REVIEW

**Comment by leoplo** [comment]
@pedrofran12 this is still untested yet but I wanted to open the PR to discuss about supporting Python 3.11 for https://github.com/pedrofran12/pim_dm .

**Comment by pedrofran12** [comment]
Hi @leoplo ,

Thank you for your continuous help in supporting this project!!

I will check netifaces2... or maybe another package with long term support. If I am not mistaken I don't do much with netifaces... mainly get interfaces and their IP.

Regarding IGMPv3, we already have a working version... I will ask the student to open a PR and then I work on it to be generic to support both PIM-DM and HPIM-DM.

Thank you again!!
-Pedro

**Comment by pedrofran12** [comment]
Hi @leoplo,

I have tried the existing netifaces on Python 3.11 and it works well for the type of workflow we currently do: just listing interfaces and getting their IPs.

Did you find any specific issue that forces we to move to netifaces2 or other package?

Happy new year :)
-Pedro

**Comment by jhg8** [comment]
Hi @pedrofran12 , I work with Léo-Paul on this subject, initially I had some issues when trying to install pim-dm with python3.11 and when I saw that netifaces was unmaintained and only supporting python up to 3.8 I thought it would be necessary to make the switch to netifaces2, but I didn't find any specific issue and maybe it is not necessary. (Checking again I see that the issues I had were due to pcap.c file in pim-dm repository).

Happy new year !

**Comment by leoplo** [comment]
Happy new year !

So I tested the installation through pip and there is indeed no problem with `netifaces`. Therefore I will close both this PR and the one for [mld](https://github.com/pedrofran12/mld/pull/14).

As for the `pcap.c` I will open a PR in [pim-dm](https://github.com/pedrofran12/pim_dm) repository. To solve the compatibility problem I revomed the `pcap.c` file and it will now be generated during pip installation.

**Pull request closed without merging**
